SELECT * FROM RRHH.TT_DEPENDENCIA_RH_CIDEJ;
  
update RRHH.TT_DEPENDENCIA_RH_CIDEJ set ID_DESPACHO= null;
  
alter table RRHH.TT_DEPENDENCIA_RH_CIDEJ modify ID_DESPACHO varchar2(5);
  

SELECT * FROM SIDEP.TT_DEPENDENCIA_RH_CIDEJ;

update SIDEP.TT_DEPENDENCIA_RH_CIDEJ set ID_DESPACHO= null;
  
alter table SIDEP.TT_DEPENDENCIA_RH_CIDEJ  modify ID_DESPACHO varchar2(5);
