Insert into TS_ESTADO_PROCESO (ID_ESTADO_PROCESO,ESTADO_PROCESO,ID_SOURCE,ID_ESTADO,FECHA_CREACION,OBSERVACIONES,ID_USUARIO_REGISTRO)
values ('27','ESTADO RECHAZO','1','1',to_date('06/08/22','DD/MM/RR'),'RECHAZOS','27815');
