--Drop table SIDEP.RH_AREA_DEPARTAMENTO;
--
-- RH_AREA_DEPARTAMENTO  (Table) 
--
ALTER TABLE SIDEP.RH_AREA_DEPARTAMENTO ADD  ESTADO VARCHAR2(1 BYTE) default 'S'; 

CREATE TABLE SIDEP.RH_AREA_DEPARTAMENTO
(
  CODIGO_AREA                    NUMBER      NOT NULL,
  NOMBRE_AREA                    VARCHAR2(300 BYTE) NOT NULL,
  DESCRIPCION_AREA               VARCHAR2(500 BYTE) NOT NULL,
  AREA_PADRE                     NUMBER      NOT NULL
)
/
COMMENT ON COLUMN SIDEP.RH_AREA_DEPARTAMENTO.CODIGO_AREA IS 'Codigo de las diferentes areas creadas en el OJ';
COMMENT ON COLUMN SIDEP.RH_AREA_DEPARTAMENTO.NOMBRE_AREA IS 'Nombre de las diferentes areas creadas en el OJ';
COMMENT ON COLUMN SIDEP.RH_AREA_DEPARTAMENTO.DESCRIPCION_AREA IS 'Descripcion de las diferentes areas creadas en el OJ';
COMMENT ON COLUMN SIDEP.RH_AREA_DEPARTAMENTO.AREA_PADRE IS 'Codigo area principal';
/


CREATE UNIQUE INDEX RRHH.PK_RH_AREA_DEPARTAMENT ON SIDEP.RH_AREA_DEPARTAMENTO
(CODIGO_AREA)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

ALTER TABLE SIDEP.RH_AREA_DEPARTAMENTO ADD (
  CONSTRAINT PK_RH_AREA_DEPARTAMENT
  PRIMARY KEY(CODIGO_AREA)
  USING INDEX RRHH.PK_RH_AREA_DEPARTAMENT
  ENABLE VALIDATE);
  
  --
-- SQ_TT_DEPENDENCIA_CORREO  (Sequence) 
-- 
--DROP SEQUENCE SIDEP.SQ_RH_AREA_DEPARTAMENTO;

CREATE SEQUENCE SIDEP.SQ_RH_AREA_DEPARTAMENTO
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;
/
    Select * from RH_AREA_DEPARTAMENTO;