
--
-- PKG_DEPENDENCIA_VALIDACIONES  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY SIDEP.PKG_DEPENDENCIA_VALIDACIONES AS

FUNCTION FUNC_VALIDA_COD_DEPENDENCIA(
        P_CODIGO_DEPENDENCIA NUMBER) RETURN NUMBER IS
        P_VALIDA NUMBER := 0;
    BEGIN
            SELECT COUNT(*) INTO P_VALIDA FROM RRHH.RH_DEPENDENCIA WHERE DEPENDENCIA = P_CODIGO_DEPENDENCIA;
        RETURN P_VALIDA;
    END FUNC_VALIDA_COD_DEPENDENCIA;
    
    
    FUNCTION FUNC_VALIDA_COD_PRESUPUESTARIO(
        P_CODIGO_DEPENDENCIA NUMBER) RETURN NUMBER IS
        P_VALIDA NUMBER := 0;
    BEGIN
            SELECT COUNT(*) INTO P_VALIDA FROM RRHH.RH_DEPENDENCIA WHERE CODIGO_PRESUPUESTARIO = P_CODIGO_DEPENDENCIA;
        RETURN P_VALIDA;
    END FUNC_VALIDA_COD_PRESUPUESTARIO;
    
    FUNCTION FUNC_VALIDA_COD_DEP_SOLICITUD(
        P_CODIGO_DEPENDENCIA NUMBER) RETURN NUMBER IS
         P_VALIDA NUMBER := 0;
    BEGIN
        SELECT COUNT(*) INTO P_VALIDA FROM SIDEP.TT_GEST_DEPENDENCIA WHERE CODIGO_DEPENDENCIA = P_CODIGO_DEPENDENCIA 
        AND ID_ESTADO=1;
        RETURN P_VALIDA;
    END FUNC_VALIDA_COD_DEP_SOLICITUD;
    
    FUNCTION FUNC_VALIDA_SOLICITUD_CREACION(
        P_CODIGO_DEPENDENCIA NUMBER) RETURN NUMBER IS
        P_VALIDA NUMBER := 0;
        BEGIN
            SELECT COUNT(*) INTO P_VALIDA FROM SIDEP.TT_GEST_DEPENDENCIA WHERE CODIGO_DEPENDENCIA = P_CODIGO_DEPENDENCIA AND ID_ESTADO = 1;
        RETURN P_VALIDA;
    END FUNC_VALIDA_SOLICITUD_CREACION;  
    
END PKG_DEPENDENCIA_VALIDACIONES;