CREATE TABLE RRHH.RH_DEPARTAMENTO
(
  PAIS                      NUMBER(3)           NOT NULL,
  DEPARTAMENTO              NUMBER(3)           NOT NULL,
  NOMBRE_DEPARTAMENTO       VARCHAR2(30 BYTE)   NOT NULL,
  ABREVIATURA_DEPARTAMENTO  VARCHAR2(5 BYTE)    NOT NULL,
  AREA                      VARCHAR2(1 BYTE)    DEFAULT 'P'                   NOT NULL,
  CODIGO_PRESUPUESTARIO     NUMBER(4)           NOT NULL,
  CUOTA_LABORAL_IGSS        NUMBER(8,4)         DEFAULT 0                     NOT NULL,
  CUOTA_PATRONAL_IGSS       NUMBER(8,4)         DEFAULT 0                     NOT NULL,
  CODIGO_BANCARIO           NUMBER(3),
  AREA_GEOGRAFICA           CHAR(1 BYTE)        DEFAULT 'C'                   NOT NULL,
  ID_CEDULA                 VARCHAR2(3 BYTE),
  UCIORDEN                  NUMBER(3)           DEFAULT 999
)
/

COMMENT ON TABLE RRHH.RH_DEPARTAMENTO IS 'Descripcion general de los Departamentos y/o Provincias del Pais';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.PAIS IS 'Codigo del pais';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.DEPARTAMENTO IS 'Codigo del departamento o provincia';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.NOMBRE_DEPARTAMENTO IS 'Nombre del departamento o provincia';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.ABREVIATURA_DEPARTAMENTO IS 'Abreviatura del departamento';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.AREA IS 'Area geografica donde se encuentra el departamento, CENTRAL, OCCIDENTE, ORIENTE, NORTE, SUR.';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.CODIGO_PRESUPUESTARIO IS 'Codigo presupestario definido para este departamento';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.CUOTA_LABORAL_IGSS IS 'Porcentaje de la cuota laboral del IGSS para el OJ, segun el departamento.';
/
COMMENT ON COLUMN RRHH.RH_DEPARTAMENTO.CUOTA_PATRONAL_IGSS IS 'Cuotra patronal de IGSS';
/

CREATE INDEX RRHH.XIF2DEPARTAMENTO ON RRHH.RH_DEPARTAMENTO
(PAIS)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RRHH.XPKDEPARTAMENTO ON RRHH.RH_DEPARTAMENTO
(PAIS, DEPARTAMENTO)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


GRANT SELECT ON RRHH.RH_DEPARTAMENTO TO SIDEP;
/


CREATE TABLE RRHH.RH_MUNICIPIO
(
  PAIS                         NUMBER(3)        NOT NULL,
  DEPARTAMENTO                 NUMBER(3)        NOT NULL,
  MUNICIPIO                    NUMBER(3)        NOT NULL,
  NOMBRE_MUNICIPIO             VARCHAR2(30 BYTE) NOT NULL,
  ABREVIATURA_MUNICIPIO        VARCHAR2(5 BYTE) NOT NULL,
  FECHA_FERIA_LOCAL            DATE             DEFAULT sysdate               NOT NULL,
  FERIA_LOCAL_FIJO             CHAR(1 BYTE)     DEFAULT 'S'                   NOT NULL,
  USUARIO_DEFINIO_FERIA_LOCAL  VARCHAR2(40 BYTE) DEFAULT USER NOT NULL,
  FECHA_ULTIMA_MODIFICACION    DATE             DEFAULT SYSDATE               NOT NULL,
  OBSERVACIONES                VARCHAR2(128 BYTE)
)
/

COMMENT ON TABLE RRHH.RH_MUNICIPIO IS 'Descripcion general de los municipios departamentales.';
/
COMMENT ON COLUMN RRHH.RH_MUNICIPIO.PAIS IS 'Codigo del pais';
/
COMMENT ON COLUMN RRHH.RH_MUNICIPIO.DEPARTAMENTO IS 'Codigo del departamento o provincia';
/
COMMENT ON COLUMN RRHH.RH_MUNICIPIO.MUNICIPIO IS 'Codigo del municipio';
/

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.NOMBRE_MUNICIPIO IS 'Nombre del municipio';
/
COMMENT ON COLUMN RRHH.RH_MUNICIPIO.ABREVIATURA_MUNICIPIO IS 'Abreviatura del municipio departamenta';
/



CREATE UNIQUE INDEX RRHH.XPKMUNICIPIO ON RRHH.RH_MUNICIPIO
(PAIS, DEPARTAMENTO, MUNICIPIO)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RRHH.RH_MUNICIPIO ADD (
  CONSTRAINT CK_FERIA_LOCAL_FIJO
  CHECK (feria_local_fijo in ( 'S', 'N' ))
  ENABLE VALIDATE,
  CONSTRAINT XPKMUNICIPIO
  PRIMARY KEY
  (PAIS, DEPARTAMENTO, MUNICIPIO)
  USING INDEX RRHH.XPKMUNICIPIO
  ENABLE VALIDATE);
/
ALTER TABLE RRHH.RH_MUNICIPIO ADD (
  CONSTRAINT R_MUNICIPIO_DEPARTAMENTO 
  FOREIGN KEY (PAIS, DEPARTAMENTO) 
  REFERENCES RRHH.RH_DEPARTAMENTO (PAIS,DEPARTAMENTO)
  ENABLE VALIDATE);
/

GRANT SELECT ON RRHH.RH_MUNICIPIO TO SIDEP;
/


CREATE TABLE RRHH.RH_TIPO_AREA
(
  ID_AREA      NUMBER(2)                        NOT NULL,
  NOMBRE_AREA  VARCHAR2(50 BYTE)                NOT NULL
)
/

COMMENT ON TABLE RRHH.RH_TIPO_AREA IS 'CONTENDRA EL CATALOGO DE LAS CLASIFICACION DE LAS DEPENDENCIAS POR AREA 1=JURIS, 2=ADMITIVA, ETC.';

COMMENT ON COLUMN RRHH.RH_TIPO_AREA.ID_AREA IS 'IDENTIFICACION DEL CODIGO DE AREA';

COMMENT ON COLUMN RRHH.RH_TIPO_AREA.NOMBRE_AREA IS 'NOMBRE DESIGNADO AL REA';



CREATE INDEX RRHH.IDX_NOMREAREA ON RRHH.RH_TIPO_AREA
(NOMBRE_AREA)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RRHH.PK_RH_TIPO_AREA ON RRHH.RH_TIPO_AREA
(ID_AREA)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE PUBLIC SYNONYM RH_TIPO_AREA FOR RRHH.RH_TIPO_AREA;


ALTER TABLE RRHH.RH_TIPO_AREA ADD (
  CONSTRAINT PK_RH_TIPO_AREA
  PRIMARY KEY
  (ID_AREA)
  USING INDEX RRHH.PK_RH_TIPO_AREA
  ENABLE VALIDATE);


GRANT SELECT ON RRHH.RH_TIPO_AREA TO SIDEP;

