SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT * FROM RRHH.RH_DEPARTAMENTO;
--
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 2, 'SACATEPEQUEZ', 'SAC', 'C', 
    301, 3, 7, 16, 'C', 
    'B02', 16);
    
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 1, 'GUATEMALA', 'GT', 'C', 
    101, 3, 7, 14, 'C', 
    'A01', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 3, 'CHIMALTENANGO', 'CHI', 'C', 
    401, 3, 7, 16, 'C', 
    'C03', 3);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 4, 'EL PROGRESO', 'EL', 'E', 
    201, 3, 7, 16, 'E', 
    'D04', 5);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 5, 'ESCUINTLA', 'ESC', 'C', 
    500, 3, 7, 16, 'C', 
    'E05', 7);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 6, 'SANTA ROSA', 'SAN', 'E', 
    600, 3, 7, 16, 'E', 
    'F06', 18);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 7, 'SOLOLÁ', 'SOL', 'O', 
    700, 3, 7, 16, 'O', 
    'G07', 19);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 8, 'TOTONICAPAN', 'TOT', 'O', 
    800, 3, 7, 16, 'O', 
    'H08', 21);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 9, 'QUETZALTENANGO', 'QUE', 'O', 
    900, 3, 7, 16, 'O', 
    'I09', 14);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 10, 'SUCHITEPEQUEZ', 'SUC', 'O', 
    1000, 3, 7, 16, 'O', 
    'J10', 20);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 11, 'RETALHULEU', 'RET', 'O', 
    1100, 3, 7, 16, 'O', 
    'K11', 15);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 12, 'SAN MARCOS', 'SAN', 'O', 
    1200, 3, 7, 16, 'O', 
    'L12', 17);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 13, 'HUEHUETENANGO', 'HUE', 'O', 
    1300, 3, 7, 16, 'O', 
    'M13', 9);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 14, 'EL QUICHE', 'EL', 'O', 
    1400, 3, 7, 16, 'O', 
    'N14', 6);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 15, 'BAJA VERAPAZ', 'BAJ', 'N', 
    1500, 3, 7, 16, 'N', 
    'Ñ15', 2);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 16, 'ALTA VERAPAZ', 'ALT', 'N', 
    1600, 3, 7, 16, 'N', 
    'O16', 1);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 17, 'PETEN', 'PETEN', 'N', 
    1700, 3, 7, 16, 'N', 
    'P17', 13);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 18, 'IZABAL', 'IZA', 'N', 
    1800, 3, 7, 16, 'N', 
    'Q18', 10);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 19, 'ZACAPA', 'ZAC', 'E', 
    1900, 3, 7, 16, 'E', 
    'R19', 22);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 20, 'CHIQUIMULA', 'CHI', 'E', 
    2000, 3, 7, 16, 'E', 
    'S20', 4);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 21, 'JALAPA', 'JAL', 'E', 
    2100, 3, 7, 16, 'E', 
    'T21', 11);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, CODIGO_BANCARIO, AREA_GEOGRAFICA, 
    ID_CEDULA, UCIORDEN)
 Values
   (1, 22, 'JUTIAPA', 'JUT', 'E', 
    2200, 3, 7, 16, 'E', 
    'U22', 12);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (2, 1, 'EL SALVADOR', 'SALV', 'C', 
    1, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (3, 1, 'TEGUCIGALPA', 'TEG', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (4, 1, 'MANAGUA', 'MAN', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (5, 1, 'SAN JOSE', 'SJ', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (6, 1, 'PANAMA', 'PAN', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (7, 1, 'MEXICO, D.F.', 'MEX', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (9, 1, 'HOUSTON', 'HST', 'C', 
    0, 0, 0, 'C', 8);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (2, 2, 'LA PAZ', 'PAZ', 'C', 
    1, 0, 0, 'C', 999);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (1, 300, 'MULTIREGIONAL', 'MTR', 'C', 
    3000, 3, 7, 'C', 999);
Insert into RRHH.RH_DEPARTAMENTO
   (PAIS, DEPARTAMENTO, NOMBRE_DEPARTAMENTO, ABREVIATURA_DEPARTAMENTO, AREA, 
    CODIGO_PRESUPUESTARIO, CUOTA_LABORAL_IGSS, CUOTA_PATRONAL_IGSS, AREA_GEOGRAFICA, UCIORDEN)
 Values
   (8, 1, 'BOGOTA', 'BOG', 'C', 
    0, 0, 0, 'C', 8);
COMMIT;