INSERT INTO "SIDEP"."TS_SOURCE" (ID_SOURCE, SOURCE) VALUES ('1', 'BD')
/
INSERT INTO "SIDEP"."TS_SOURCE" (ID_SOURCE, SOURCE) VALUES ('2', 'APP')
/
INSERT INTO "SIDEP"."TS_ESTADO" (ID_ESTADO, ESTADO, FECHA_CREACION,OBSERVACIONES, ID_SOURCE, ACTIVO)
VALUES ('1', 'Activo', TO_DATE('2022-08-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),'PRIMER ESTADO DE PRUEBA', '1', '1');
/
INSERT INTO "SIDEP"."TS_ESTADO" (ID_ESTADO, ESTADO, FECHA_CREACION, OBSERVACIONES,ID_SOURCE, ACTIVO) 
VALUES ('2', 'Inactivo', TO_DATE('2022-08-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SEGUNDO ESTADO DE PRUEBA','1', '1');
/
